name: Build on release

on:
  release:
    types: [published]
  push:
    tags:
      - '*'

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: get-release
        uses: rez0n/actions-github-release@main
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "supabase/remco"
          type: "stable"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: build distribution
        run: |
          export VERSION=$(git describe --tags --always --dirty --first-parent)
          GOARCH=arm64 make release
          mkdir dist
          mv bin/*zip dist/
          make clean
          GOARCH=amd64 make release
          mv bin/*zip dist/

      - uses: AButler/upload-release-assets@v2.0
        with:
          files: "dist/*zip"
          release-tag: ${{ steps.releases.outputs.release }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
