name: Build on release

on:
  push:
    branches:
      - da/test

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: build distribution
        run: |
          export VERSION=$(git describe --tags --always --dirty --first-parent)
          make test
